// Pro rata SOL distribution to the 100 current on chain NFT holders.
//
// Use this after every piece has been airdropped out of the deployer wallet:
// the deployer's SOL balance accumulates from pump.fun $ART creator fees and
// the 5% NFT royalty stream on Magic Eden / Tensor. This script:
//
//   1. Reads the live on chain holders (output/winners/onchain-owners.json,
//      regenerated by scripts/onchain-owners.js).
//   2. Refuses to run unless all 100 assets are held by non deployer wallets
//      (full mintout is the precondition the holders were promised).
//   3. Distributes lamports pro rata: each rank gets an equal share. If one
//      wallet holds several pieces it receives several shares, which is
//      strict pro rata across the collection.
//   4. Saves an idempotent per epoch state: a re run with the same epoch
//      resumes any unsent ranks instead of double paying.
//
//   node scripts/distribute-fees.js                                 # dry
//   node scripts/distribute-fees.js --execute                       # send
//   node scripts/distribute-fees.js --execute --amount 3000000000   # 3 SOL
//   node scripts/distribute-fees.js --execute --epoch 2026-06-01    # named epoch

import fs from "node:fs";
import path from "node:path";
import {
  Connection, Keypair, PublicKey, SystemProgram, Transaction,
  sendAndConfirmTransaction, LAMPORTS_PER_SOL,
} from "@solana/web3.js";
import { config } from "../src/config.js";
import { loadDeployerKeypair } from "../src/lib/wallet.js";

const args = process.argv.slice(2);
const argVal = (k) => {
  const i = args.indexOf(k);
  return i === -1 ? null : args[i + 1];
};
const dry = !args.includes("--execute");
const explicitAmount = argVal("--amount") ? Number(argVal("--amount")) : null;
const epoch = argVal("--epoch") || new Date().toISOString().replace(/[:.]/g, "_");

const RESERVE_LAMPORTS = Number(process.env.DEPLOYER_SOL_RESERVE || 500_000_000); // 0.5 SOL

const winDir = path.join(config.root, "output", "winners");
const ownersPath = path.join(winDir, "onchain-owners.json");
const statePath = path.join(winDir, "distribution-state.json");

if (!fs.existsSync(ownersPath)) {
  console.error(`Missing ${ownersPath}. Run scripts/onchain-owners.js first.`);
  process.exit(1);
}
const owners = JSON.parse(fs.readFileSync(ownersPath, "utf8"));
const state = fs.existsSync(statePath)
  ? JSON.parse(fs.readFileSync(statePath, "utf8"))
  : { epochs: {} };
const save = () => fs.writeFileSync(statePath, JSON.stringify(state, null, 2));

const deployer = loadDeployerKeypair();
const DEP = deployer.publicKey.toBase58();

// Mintout precondition.
const ranks = Object.keys(owners.byRank).map(Number).sort((a, b) => a - b);
if (ranks.length !== 100) {
  console.error(`onchain-owners has ${ranks.length} entries, need 100. Regenerate after mint.`);
  process.exit(1);
}
const stillWithDeployer = ranks.filter((r) => owners.byRank[r] === DEP);
if (stillWithDeployer.length > 0) {
  console.error(
    `Cannot distribute: ${stillWithDeployer.length} pieces are still in the artist wallet. ` +
      `Full mintout is the precondition. Ranks: ${stillWithDeployer.slice(0, 10).join(",")}${stillWithDeployer.length > 10 ? "..." : ""}.`
  );
  process.exit(1);
}

const conn = new Connection(config.solana.rpcUrl(), "confirmed");

async function main() {
  const balance = await conn.getBalance(deployer.publicKey);
  const free = Math.max(0, balance - RESERVE_LAMPORTS);
  const totalLamports = explicitAmount != null ? explicitAmount : free;
  if (totalLamports <= 0) {
    console.log(`Nothing to distribute. balance=${(balance / LAMPORTS_PER_SOL).toFixed(6)} SOL, reserve=${RESERVE_LAMPORTS / LAMPORTS_PER_SOL} SOL.`);
    return;
  }
  if (totalLamports > free && explicitAmount != null) {
    console.error(
      `Refusing: requested ${totalLamports} lamports exceeds balance minus reserve (${free}).`
    );
    process.exit(1);
  }
  const share = Math.floor(totalLamports / 100);
  const sent = totalLamports - share * 100; // dust kept in deployer

  console.log(`Deployer: ${DEP}`);
  console.log(`Balance: ${(balance / LAMPORTS_PER_SOL).toFixed(6)} SOL`);
  console.log(`Reserve: ${(RESERVE_LAMPORTS / LAMPORTS_PER_SOL).toFixed(6)} SOL`);
  console.log(`Distributing: ${(totalLamports / LAMPORTS_PER_SOL).toFixed(6)} SOL = 100 shares of ${(share / LAMPORTS_PER_SOL).toFixed(9)} SOL (dust ${sent} lamports remains)`);
  console.log(`Epoch: ${epoch}  Mode: ${dry ? "DRY" : "EXECUTE"}`);

  const ep = state.epochs[epoch] || {
    startedAt: new Date().toISOString(),
    totalLamports,
    share,
    byRank: {},
  };
  state.epochs[epoch] = ep;
  if (ep.totalLamports !== totalLamports || ep.share !== share) {
    if (Object.keys(ep.byRank).some((r) => ep.byRank[r].sig)) {
      console.error(
        `Epoch ${epoch} was already partially executed with share=${ep.share}. ` +
          `Refusing to resume with a different share=${share}. Pick a new --epoch.`
      );
      process.exit(1);
    }
    ep.totalLamports = totalLamports;
    ep.share = share;
  }

  let toSend = 0;
  for (const r of ranks) {
    if (!ep.byRank[r]?.sig) toSend++;
  }
  console.log(`Plan: ${toSend} of 100 ranks pending in this epoch.`);

  if (dry) {
    for (const r of ranks.slice(0, 5)) {
      console.log(`  #${String(r).padStart(3, "0")} -> ${owners.byRank[r]}  ${(share / LAMPORTS_PER_SOL).toFixed(9)} SOL${ep.byRank[r]?.sig ? "  (already sent)" : ""}`);
    }
    console.log(`  ... 100 total`);
    return;
  }

  let count = 0;
  for (const r of ranks) {
    if (ep.byRank[r]?.sig) continue;
    const to = owners.byRank[r];
    try {
      const tx = new Transaction().add(
        SystemProgram.transfer({
          fromPubkey: deployer.publicKey,
          toPubkey: new PublicKey(to),
          lamports: share,
        })
      );
      const sig = await sendAndConfirmTransaction(conn, tx, [deployer], {
        commitment: "confirmed",
      });
      ep.byRank[r] = { to, sig, sentAt: new Date().toISOString() };
      save();
      count++;
      console.log(`  #${String(r).padStart(3, "0")} -> ${to.slice(0, 8)}.. ${sig.slice(0, 16)}..`);
    } catch (e) {
      console.error(`  #${String(r).padStart(3, "0")} FAILED: ${e.message}`);
      process.exitCode = 1;
    }
  }
  console.log(`\nSent this run: ${count}. Resume with --epoch ${epoch} to retry any failures.`);
}
main().catch((e) => { console.error(e); process.exit(1); });
